### ISSUE TITLE
老兄你好，希望能为你的项目提供PR

### ISSUE THREAD

**Issue by jorschac** [kikyous/vscode-css-action#2]
老兄你好，我们是美团的基础架构团队，我们团队现在正在大规模进行设计变量替换样式值的升级，虽然没有直接安装你开发的拓展，但是在你开源代码的基础上做了一些修改，目前相关能力建设已在团队内大范围落地。基于我们的使用经验，我个人希望对你的项目提一些PR，主要解决以下问题：

  - 变量声明文件只接受本地路径，生产环境中许多变量声明文件是以CDN的形式下发的，缺少拉取解析CDN资源的能力
  - 文件解析失败时缺少兜底逻辑
  - 缺少对圆角和字号、渐变色的支持

如果您同意我的PR申请，请尽快回复我的issue，如果有进一步的问题，欢迎加我的微信详谈：jorschac

**Comment by jorschac** [comment]
感谢感谢

**Comment by jorschac** [comment]
误点close

**Comment by kikyous** [comment]
这个项目还有很多不足，欢迎PR

**Comment by jorschac** [comment]
> 这个项目还有很多不足，欢迎PR
好的 感谢
